// LOCALHOST
###
GET http://localhost:8080/
###
GET http://localhost:8080/awesome
###
GET http://localhost:8080/awesome2

### Get all contacts
GET http://localhost:8080/contacts

### Get contacts by id
GET http://localhost:8080/contacts/6637070845d675983b875cf1
###
GET http://localhost:8080/contacts/6637070845d675983b875cf2
###
GET http://localhost:8080/contacts/663d9c34a74354e3b94af183
###
GET http://localhost:8080/contacts/663ec810aaec4375d8f0e366

### Create contact
POST http://localhost:8080/contacts HTTP/1.1
content-type: application/json

{
    "firstName":"Frank",
    "lastName":"Powell",
    "email":"Frank.Powell@mailtest.com",
    "favoriteColor":"Red",
    "birthday":"08/11/1977"
}

### PUT contact
PUT http://localhost:8080/contacts/663ee069ab85ae392d0f7077 HTTP/1.1
content-type: application/json

{
    "firstName":"Frank",
    "lastName":"Powell",
    "email":"Frank.Powell@mailtest.com",
    "favoriteColor":"Purple",
    "birthday":"01/15/1950"
}

### DELETE contact
DELETE http://localhost:8080/contacts/663ee069ab85ae392d0f7077 



// PRODUCTION Deploy

### Get all contacts on production
GET https://cse341-jb.onrender.com/contacts HTTP/1.1


### Create contact on production
POST https://cse341-jb.onrender.com/contacts HTTP/1.1
content-type: application/json

{
    "firstName":"Courtney",
    "lastName":"Purser",
    "email":"Courtney.Purser@mailtest.com",
    "favoriteColor":"Red",
    "birthday":"08/26/1985"
}


### PUT contact on production
PUT https://cse341-jb.onrender.com/contacts/663ee136c8f2b27c06ddad46 HTTP/1.1
content-type: application/json

{
    "firstName":"Jake",
    "lastName":"Olsen",
    "email":"Jake.Olsen@mailtest.com",
    "favoriteColor":"Red",
    "birthday":"04/12/1983"
}

### DELETE contact on production
DELETE https://cse341-jb.onrender.com/contacts/663ee1bdc8f2b27c06ddad47 HTTP/1.1

